In [1]:
import pandas as pd

# Changing the Money variable to an integer

In [2]:
df = pd.read_csv("../Data Analytics Projects/PGA_Tour_cleaned.csv")
df

,Unnamed: 0,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,0.0,5.000000,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,1.0,3.000000,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,0.0,3.000000,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,0.0,5.000000,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,0.0,3.000000,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1669,1673,Phil Mickelson,76.0,52.66,2010,299.1,65.13,28.79,61.84,69.966,1.0,5.000000,-0.147,1.001,0.185,0.738,0.228,"3,821,733"
1670,1674,John Daly,63.0,52.21,2010,305.7,65.66,29.78,53.53,71.697,0.0,2.892092,-0.653,-0.989,0.336,-0.374,-0.298,"158,587"
1671,1675,Jimmy Walker,82.0,51.29,2010,292.9,65.88,29.14,58.46,70.953,0.0,2.000000,0.252,0.093,-0.538,0.336,0.047,"937,987"
1672,1676,Daniel Chopra,74.0,51.27,2010,295.9,61.64,28.88,56.16,72.194,0.0,2.892092,0.361,-1.096,-0.307,-1.070,-0.084,"311,405"
1673,1677,Martin Flores,75.0,50.15,2010,300.7,64.79,29.41,54.00,71.882,0.0,1.000000,-0.106,-0.883,-0.223,-0.553,-0.001,"318,673"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1674 entries, 0 to 1673
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1674 non-null   int64
 1   Player Name         1674 non-null   object
 2   Rounds              1674 non-null   float64
 3   Fairway Percentage  1674 non-null   float64
 4   Year                1674 non-null   int64
 5   Avg Distance        1674 non-null   float64
 6   gir                 1674 non-null   float64
 7   Average Putts       1674 non-null   float64
 8   Average Scrambling  1674 non-null   float64
 9   Average Score       1674 non-null   float64
 10  Wins                1674 non-null   float64
 11  Top 10              1674 non-null   float64
 12  Average SG Putts    1674 non-null   float64
 13  Average SG Total    1674 non-null   float64
 14  SG:OTT              1674 non-null   float64
 15  SG:APR              1674 non-null   float64
 16  SG:ARG              1674 non-null   float64
 17  Money               1674 non-null   object
dtypes: float64(14), int64(2), object(2)
memory usage: 235.5+ KB

In [4]:
df['Money'] = df['Money'].replace('[\$,]', '', regex=True).astype(int)

In [5]:
print(df['Money'].dtype)
print(df['Money'].head())

int64
0    2680487
1    2485203
2    2700018
3    1986608
4    1089763
Name: Money, dtype: int64

In [6]:
df.to_csv("../Data Analytics Projects/PGA_Tour_cleaned1.csv")