In [1]:
import pandas as pd

In [6]:
data = pd.read_csv("../Data Analytics Projects/pgaTourData.csv")

In [7]:
data.head()

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Points,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,868,NaN,5.0,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,"1,006",1.0,3.0,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,"1,020",NaN,3.0,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,795,NaN,5.0,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,421,NaN,3.0,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"

In [8]:
# finding null values
data.isna()

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Points,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2307,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2308,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2309,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2310,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2311,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False

# Dropping unnecessary columns

In [10]:
# Dropping Points column as it adds no real value

data.drop(columns=["Points"], inplace=True)

data

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,NaN,5.0,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,1.0,3.0,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,NaN,3.0,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,NaN,5.0,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,NaN,3.0,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2307,Carl Paulson,NaN,NaN,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$16,943"
2308,Peter Tomasulo,NaN,NaN,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$12,827"
2309,Marc Turnesa,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,159"
2310,Jesper Parnevik,NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9,165"
2311,"Jim Gallagher, Jr.",NaN,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,552"

# Deleting rows with more than 50% of data missing

In [22]:
threshold = len(data.columns) / 2

# Identify rows where the number of missing values is greater than the threshold
rows_with_majority_missing = data.isnull().sum(axis=1) > threshold

# Drop these rows from the DataFrame
data_cleaned = data[~rows_with_majority_missing]

data_cleaned

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,NaN,5.0,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,1.0,3.0,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,NaN,3.0,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,NaN,5.0,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,NaN,3.0,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,Phil Mickelson,76.0,52.66,2010,299.1,65.13,28.79,61.84,69.966,1.0,5.0,-0.147,1.001,0.185,0.738,0.228,"3,821,733"
1674,John Daly,63.0,52.21,2010,305.7,65.66,29.78,53.53,71.697,NaN,NaN,-0.653,-0.989,0.336,-0.374,-0.298,"158,587"
1675,Jimmy Walker,82.0,51.29,2010,292.9,65.88,29.14,58.46,70.953,NaN,2.0,0.252,0.093,-0.538,0.336,0.047,"937,987"
1676,Daniel Chopra,74.0,51.27,2010,295.9,61.64,28.88,56.16,72.194,NaN,NaN,0.361,-1.096,-0.307,-1.070,-0.084,"311,405"
1677,Martin Flores,75.0,50.15,2010,300.7,64.79,29.41,54.00,71.882,NaN,1.0,-0.106,-0.883,-0.223,-0.553,-0.001,"318,673"

# Replacing missing data

In [40]:
# Calculate the mean of the "Top 10" column
top_10_mean = data_cleaned['Top 10'].mean()

# Define fill values for each column
fill_values = {"Wins": 0, "Top 10": top_10_mean}

# Fill missing values using fillna() with the specified fill values
data_cleaned.fillna(value=fill_values, inplace=True)


data_cleaned

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60.0,75.19,2018,291.5,73.51,29.93,60.67,69.617,0.0,5.000000,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109.0,73.58,2018,283.5,68.22,29.31,60.13,70.758,1.0,3.000000,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93.0,72.24,2018,286.5,68.67,29.12,62.27,70.432,0.0,3.000000,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78.0,71.94,2018,289.2,68.80,29.17,64.16,70.015,0.0,5.000000,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103.0,71.44,2018,278.9,67.12,29.11,59.23,71.038,0.0,3.000000,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,Phil Mickelson,76.0,52.66,2010,299.1,65.13,28.79,61.84,69.966,1.0,5.000000,-0.147,1.001,0.185,0.738,0.228,"3,821,733"
1674,John Daly,63.0,52.21,2010,305.7,65.66,29.78,53.53,71.697,0.0,2.892092,-0.653,-0.989,0.336,-0.374,-0.298,"158,587"
1675,Jimmy Walker,82.0,51.29,2010,292.9,65.88,29.14,58.46,70.953,0.0,2.000000,0.252,0.093,-0.538,0.336,0.047,"937,987"
1676,Daniel Chopra,74.0,51.27,2010,295.9,61.64,28.88,56.16,72.194,0.0,2.892092,0.361,-1.096,-0.307,-1.070,-0.084,"311,405"
1677,Martin Flores,75.0,50.15,2010,300.7,64.79,29.41,54.00,71.882,0.0,1.000000,-0.106,-0.883,-0.223,-0.553,-0.001,"318,673"

In [41]:
# deleting any rows with missing values in "Money" column
data_cleaned.dropna(subset=['Money'], inplace=True)

In [42]:
print(data_cleaned.isnull().sum())

Player Name           0
Rounds                0
Fairway Percentage    0
Year                  0
Avg Distance          0
gir                   0
Average Putts         0
Average Scrambling    0
Average Score         0
Wins                  0
Top 10                0
Average SG Putts      0
Average SG Total      0
SG:OTT                0
SG:APR                0
SG:ARG                0
Money                 0
dtype: int64

In [43]:
# save cleaned data to a new CSV file

data_cleaned.to_csv("../Data Analytics Projects/PGA_Tour_cleaned.csv")